### ISSUE TITLE
요구사항 정의서 초안

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#10]
1.    서론
-    목적
 어린이의 비속어 노출을 낮추기 위한 프로젝트의 요구사항을 정의하려 만들었다. 자체 제작 채팅 프로그램을 넘어서 학습시킨 머신러닝을 다른 프로그램으로도 보급하는 것이 목적이다.
-    요구 범위
 필터링 시스템을 파훼하기 위해 글자 사이에 다른 기호나 글자를 넣은 비속어까지 필터링 하는 것을 목표로 하고 있다.
2.    본론(요구사항)
-    비속어 필터링: 위에 명시한대로 머신러닝을 통하여 비속어와의 유사도를 비교하여 필터링할 것이다.
3.    관련 용어

#외에 추가할 내용이 있거나 수정했으면 하는 부분이 있다면 댓글로 알려주세요

**Comment by adap8709** [comment]
다소 간략하지만 좋은 것 같습니다.
멘토링 과정에서 피드백을 받을 수 있을테니 이정도로 준비해도 괜찮아보입니다.

**Comment by wan500kim** [comment]
그럼 의견이 없다고 판단하고 이슈를 닫겠습니다
