### ISSUE TITLE
1차 멘토링 준비

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#12]
요구사항정의서가 주를 이루는 멘토링이지만 프로젝트와 관련하여 질문거리가 있다면 댓글로 적어주세요

**Comment by wan500kim** [comment]
일단 저는 불확실한 프로젝트에 대해 질을 향상시킬 방향과 cnn으로 언어 모델을 만들었을 때의 정확도와 난이도에 대해 질문하려 합니다

**Comment by adap8709** [comment]
논문에서 비속어를 찾아내는 방법이 다양하여 어떠한 방법을 사용해야 하는 것이 적합할지 질문했으면 좋겠습니다.

**Comment by wan500kim** [comment]
1. 프로젝트 방향
2. cnn으로 만들 시의 장단점
3. 비속어를 찾는 효율적인 방법
위의 3개의 질문으로 정리하겠습니다
