### ISSUE TITLE
프로젝트의 차별성

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#13]
저희가 모니터 내 비속어 필터링에서 문장 내 비속어 필터링으로 주제를 바꾸며 차별성에 대해 많은 고민을 하고 있습니다.
이미 인공지능 모델을 사용한 비속어 필터링은 넘치는 상황에서 어떠한 점이 저희의 프로젝트에 특별함을 더해줄 것인지 정해야 합니다

**Comment by adap8709** [comment]
교수님께서 수업시간에 차별성에 대한 피드백이 있었습니다.
현재까지 저희 알고리즘은 지금까지의 필터링 기법과 크게 다르지 않아 이렇다 할 차별점이 없습니다.
성능 면에서라도 조금의 차별성을 만들어야 한다고 말씀하셨는데, 자신이 없네요...
차별성이 없다면 어쩔 수 없이 성능 면에서 우수하게 만들어야 하겠네요.

**Comment by wan500kim** [comment]
특정 게임에서는 비속어를 다른 단어로 1대1 치환 시스템이 사용되고 있다는 것을 알게 되었습니다.
그렇다면 저희는 1대1 치환이 아닌 문맥에 맞는 다른 단어로 교체를 하는 모델을 만드는 것은 어떨까요?
사실 저희 수준으로 가능할지는 잘 모르겠지만 충분히 차별점이 된다고 생각합니다

**Comment by adap8709** [comment]
좋은 아이디어인것 같습니다!
순화 알고리즘을 구현할 수 있을지 역시 걱정되지만 아주 좋은 차별성이 될 것 같습니다.
더 좋은 아이디어는 생각나지 않네요

**Comment by wan500kim** [comment]
그럼 저희의 차별성은 '인공지능을 사용하여 찾은 비속어를 문맥에 맞는 다른 단어로 치환하는 방식' 입니다
