### ISSUE TITLE
전처리중 특수문자 제거에 대한 딜레마

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#14]
전처리 과정에서 특수문자를 제거하는 경우에 관해 이슈가 있습니다.
본래 특수문자를 제거하는 방향으로 결정하였으나, 특수문자를 이용하여 욕설이 구성되는 경우가 존재함을 알게 되었습니다.
예를 들어 '^ㅣ발, @ㅐ미' 등의 욕설이 있습니다.

특수문자를 제거한다면 위의 욕설을 감지할 수 없게 되나, 노이즈에 취약해진다는 단점이 있습니다.
어떻게 하는 것이 좋을 지 의견을 나누고자 합니다.

**Comment by wan500kim** [comment]
관련 논문을 찾아보면 특수문자는 아니지만 비슷한 자모음에 점수를 부여하여 비속어를 찾아내는 방법이 있긴 했습니다
특수문자도 위의 방식과 같이 유사도 점수를 준다면 제거하지 않아도 될 것으로 생각이 드나 이럴 경우 아무 의미 없이 사용된 특수문자를 찾아내기에 문제가 없는지는 확실치 않습니다

**Comment by adap8709** [comment]
비슷한 논문을 찾아보았습니다.
고민한 결과 특수문자가 욕설로 사용되는 경우는 전체 경우에서 극소수의 비율이라고 판단했습니다.
따라서 약간의 취약점을 가지더라도 전체적인 정확도를 높이는 방향이 맞다 판단하여 특수문자를 제거하는 방향이 맞겠다고 판단했습니다. 어떤가요?

**Comment by wan500kim** [comment]
만약 사용에 있어 취약점이 심하게 드러난다면 그때 가서 픽스해도 괜찮을 것 같습니다. 그렇다면 특수문자는 전처리에서 빼는 방향으로 가는 것이 당장은 좋을 것 같습니다

**Comment by adap8709** [comment]
동의합니다.
