### ISSUE TITLE
1차 멘토링 내용 정리

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#15]
1. 요구사항정의서가 매우 부실하다
2. 비속어를 찾기 위해 유사도 비교를 하려면 문장이 아닌 이미지로 입력이 되어야한다
3. 문맥에 맞게 단어를 교체하는 것은 너무 어려운 도전이다

**Comment by wan500kim** [comment]
위의 3개의 내용을 각 이슈로 만들어 향후 프로젝트 방향을 조정해야 한다고 생각합니다

**Comment by adap8709** [comment]
확인했습니다. 추후에 개발 방향과 요구사항 정의서를 재조정하는 토론이 필요할 것 같네요.
