### ISSUE TITLE
요구사항정의서 수정

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#16]
멘토링 코멘트 중 하나인 요구사항 정의서를 어떻게 수정하고 살을 붙일 것인지에 대해 얘기해야 합니다

**Comment by wan500kim** [comment]
일단 저희도 다른조처럼 교수님이 올려놓으신 예시 문서와 같은 형식을 따르되 멘토님의 말씀처럼 표의 형식은 제외하는 방향은 어떨까요?

**Comment by adap8709** [comment]
결과보고서 초안을 바탕으로 양식에 맞게 내용을 수정했습니다. 확인하시고 내용이 적절한지 피드백 부탁드립니다. 
[요구사항정의서.docx](https://github.com/wan500kim/kickWorks/files/10195482/default.docx)

**Comment by wan500kim** [comment]
향후 유지보수 계획까지 작성한 것이 마음에 드네요 초안에 비해 완전 다른 문서가 되어버렸지만 좋은 변신이니 괜찮습니다

**Comment by adap8709** [comment]
알겠습니다. 새로운 의견이 있다면 말씀해주시기 바랍니다.
