### ISSUE TITLE
개발 방향 재조정

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#17]
멘토링 내용을 바탕으로 이후의 개발 방향을 조정하고자 합니다.

1. 먼저 형태소 단위 분석을 추천해 주신 것을 바탕으로 성능이 좋은 한국어 형태소 분석기를 찾아보아야 할 것 같습니다.
2. 욕설 치환 알고리즘은 문맥에 맞게 만들기는 매우 어렵다고 하셨으니 좀 더 단순한 대안이 필요해 보입니다.
3. 모델에 사용할 크롤링 데이터와 전처리 방식은 유지해도 좋을 것 같습니다.
4. 학습에 사용할 모델을 바꾸는 것이 좋을지 궁금합니다.

**Comment by wan500kim** [comment]
1. 관련하여 fasttext라는 것을 찾았습니다. 한국어 모델의 경우 이미 학습된 모델이 정식 사이트에 올려져 있습니다. 다만 사용법은 잘 모르겠습니다.
2. 그럼 문맥에 맞게 바꾼다는 부분은 제외하고 사용된 비속어의 단어의 글자수가 같은 다른 단어로 치환하는 것은 어떨까요?
3. 크롤링 데이터와 관련된 부분은 아직 열려 있는 관련 이슈 부분에서 토의합시다
4. 이미 cnn에 대해 찾아본 내용들이 있는 만큼 유지하는 쪽을 추천합니다

**Comment by adap8709** [comment]
순화 과정을 글자수만 맞추는 것으로 단순화 하는 아이디어는 좋은 것 같습니다.
그러면 fasttext와 형태소 분석기에 대해 조사해보겠습니다.
웹 구현 방향에 조정은 없으니 새로운 의견이 없다면 이슈를 닫아도 좋을 것 같습니다.
