### ISSUE TITLE
중간 발표 준비와 역할 분담

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#19]
교수님께서 말씀하신대로 프로젝트 문제와 해결법 발표에 있어 하나의 이야기가 되도록 만들었으면 합니다. 관련 스토리를 어떻게 만들 것인가 얘기하야 합니다

**Comment by wan500kim** [comment]
3주차 발표 내용대로 비속어의 사용 빈도가 높다는 내용이 좋아 바꿀 필요는 없어 보입니다. 혹시 스토리 말고도 중간 발표에 대해 건의할 내용이 있습니까?

**Comment by adap8709** [comment]
PPT 제작과 발표자 등 역할에 대해 분담하는 것이 좋겠습니다.

**Comment by wan500kim** [comment]
혹시 괜찮으시다면 ppt를 맡아주실 수 있나요? 3주차 ppt와 같은 형식으로 밀고 가는 것이 의미 있어보이기도 하고 해서..

**Comment by adap8709** [comment]
ppt를 만든 사람이 발표하지 맡는 것이 매끄럽기 때문에 제가 ppt 제작 및 발표를 맡겠습니다.
Q&A 대비를 부탁드립니다.

**Comment by wan500kim** [comment]
네 제가 QA는 하겠습니다

**Comment by adap8709** [comment]
[중간발표_[바나나킥] 김완수, 박영찬.pptx](https://github.com/wan500kim/kickWorks/files/10195805/_.pptx)
[중간발표 대본.txt](https://github.com/wan500kim/kickWorks/files/10195807/default.txt)

발표 ppt 및 대본 첨부합니다.
