### ISSUE TITLE
[주제] 문제와 주제 설정

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#2]
우리 산학 프로젝트 어떤 문제를 해결할지를 결정해야 합니다

**Comment by adap8709** [comment]
**자녀 보호 프로그램**
 설정한 시간동안 게임 등의 실행을 차단(모니터링)하는 프로그램

**Comment by wan500kim** [comment]
그건 이미 스마트폰 어플로도 많이 나와있기에 차별성을 만들기가 어렵다고 생각합니다

**Comment by wan500kim** [comment]
오히려 사용을 하는 시간이 아닌 사용을 하며 비속어 등의 안좋은 측면과의 접촉을 줄이는 방식이 어떨까요

**Comment by adap8709** [comment]
주제가 모니터링이니까 모니터상에 등장하는 모든 욕설을 검열하는 프로그램은 어떨까요?

**Comment by wan500kim** [comment]
사용하는데에 있어 불편함은 있겠지만 해결법으로 좋은 것 같아요. 저는 찬성입니다

**Comment by adap8709** [comment]
다른 아이디어가 없다면 이걸로 결정할까 하는데 어떤가요?

**Comment by wan500kim** [comment]
그럼 결정된것으로 알고 이슈를 닫겠습니다
