### ISSUE TITLE
개발 현황 파악 (1차)

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#20]
중간발표 ppt의 현재 구현 상황을 서술하기 위하여 현재 어디까지 개발이 진행되었는지 공유하고자 합니다.
각자 본인의 개발 진척도와 사진을 첨부해 주시기 바랍니다.

**Comment by adap8709** [comment]
- 일베, 유튜브에서 댓글들을 크롤링하여 비속어 데이터 수집 (완료)
![크롤러개발결과](https://user-images.githubusercontent.com/55938423/206726953-9deffb1b-c3c2-420f-851c-1391695408f3.png)

- 형태소 분리 알고리즘 (개발 중)

**Comment by wan500kim** [comment]
현재 전달받은 예시 크롤링 데이터를 자모음 단위와 형태소 단위로 나누어 출력하는 단계까지 완료해 놓았습니다. 전처리는 여기까지만 하면 되는건가요?

**Comment by adap8709** [comment]
네 사진 올려주세요

**Comment by wan500kim** [comment]
![image](https://user-images.githubusercontent.com/74997157/206727302-6bf13a27-34c6-4fc8-b974-2c7735607636.png)

형태소 단위로 나눈 모습입니다
