### ISSUE TITLE
결과보고서 초안 선행기술 조사

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#21]
결과 보고서 초안에 들어갈 저희 프로젝트와 관련된 선행기술에 대한 특허나 논문을 각 2개씩만 찾으면 될 것 같습니다

**Comment by wan500kim** [comment]
일단 제가 특허 두개를 찾아놓았습니다.
1. 한글 자모간 유사성에 기반한 비속어 검출 시스템 및 방법, 비슷한 자모음에 유사도에 따라 값을 매기는 방식입니다
2. 한국어를 위한 비속어 필터링 방법, 형태소 단위로 나누고 한글이 아닌 문자들은 미리 입력해놓은 표에 따라 비슷한 자모음으로 치환하는 방식입니다

**Comment by adap8709** [comment]
적절한 논문을 하나 찾았습니다.

### <딥러닝 기반 비속어 필터링 채팅 프로그램 설계 및 구현>
CNN으로 학습한 모델을 토대로 채팅 환경을 구현한 채팅 서비스 시스템으로, 저희 모델과 비교헀을 때
감지한 비속어를 단순히 특수문자로 마스킹하여 이용자가 비속어의 출연 여부를 즉시 알 수 있다는 문제가 있습니다.

**Comment by wan500kim** [comment]
도합 3개면 충분할 것입니다.
더이상 없다면 확인 댓글과 함께 이슈를 닫겠습니다
