### ISSUE TITLE
서비스 기대효과 및 발전방향

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#22]
결과보고서 작성에 필요한 내용입니다.
저희 서비스로 인해 기대할수 있는 효과와 발전방향을 기술해주시기 바랍니다.

**Comment by adap8709** [comment]
- 문장 내부의 비속어를 마스킹 하는 것에서 나아가, 순화한 단어로 치환함으로써 이용자가 욕설 사용 여부를 즉시 알 수 없다.
- 문맥에 따라 비속어인지 판단하여 오탐을 줄일 수 있고, 파생된 비속어를 찾아낼 수 있다.

**Comment by wan500kim** [comment]
요구사항 정의서에 적었던 '계속해서 학습시킨다'도 추가하면 좋겠습니다. 새로운 표현의 비속어가 등장해도 관련 댓글을 크롤링하여 모델만 새로 만들면 되기에 발전 방향에 적을 수 있을 것입니다.
외에도 사용자들의 댓글들을 분석한다면 취약점을 찾아내고 보완할 수 있을 것입니다.

**Comment by adap8709** [comment]
- 크롤링 기반이므로 새롭게 생겨난 비속어나 특정 커뮤니티에서 사용되는 비속어를 모델에 쉽게 업데이트 할 수 있다.
- 커뮤니티, 게임, SNS 등 인터넷 환경에 실제로 적용하여 사용자 데이터 분석 및 피드백 정보를 통해 서비스의 오탐률을 낮추고 정확도를 높일 수 있다.

위의 내용을 추가했습니다.
