### ISSUE TITLE
2차 멘토링 준비

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#23]
이번 멘토링때 멘토께 하고싶은 질문이 있으면 댓글로 적어주시기 바랍니다

**Comment by wan500kim** [comment]
저는 전처리 방식과 cnn 사용법 등이 궁금합니다. 제가 맡은건 전처리 부분이지만 cnn에 어떻게 한글 데이터를 넣어야 하는지 등 관련된 내용을 알아야 전처리도 만들 수 있기 때문입니다.
외에는 모델의 정확도에 관해 몇퍼센트 정도를 기대치로 잡아야 하는지도 여쭈어보고 싶습니다

**Comment by adap8709** [comment]
저는 현재까지 확보한 댓글 데이터와 욕설 데이터만으로 좋은 성능의 모델을 만들 수 있을 지 궁금합니다.
더 나아가 문장에서 욕설로 판단되는 단어를 찾아내려면 무엇이 더 필요한지 피드백을 받았으면 합니다.

**Comment by wan500kim** [comment]
1. 전처리 방식과 cnn모델 사용법
2. 완성된 모델 정확도의 기대치
3. 모델 정확도와 데이터의 양
4. 비속여 판별 여부에 필요한 조건
이렇게 4개의 질문으로 정리하며 이슈를 닫겠습니다
