### ISSUE TITLE
2차 멘토링 내용 정리

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#24]
2차 멘토링 내용을 요약해 보았습니다.

- 우회된 욕설을 탐지하려면 문장을 형태소로 전처리한 후. 형태소로 분류되는 단어를 제외한 나머지들을 수집하는 방법으로 구현 가능
- 모델 구현 시 워드 임베딩이 필요함. ‘한국어 임베딩’이라는 책을 참
- 현재 보유한 데이터로는 욕설 탐지 정도가 가능하나 단어를 찾기는 힘듬
- 딥러닝에는 데이터가 많이 필요하므로 높은 정확도를 기대하기 보다 80% 정도로 충분

**Comment by wan500kim** [comment]
임베딩에 관해서는 전처리 과정에 들어가는 부분인지를 더 찾아봐야 할 것 같습니다.
그리고 3번째 내용을 토대로 직접 크롤링한 데이터 말고 이미 태깅된 더 많은 양의 데이터를 찾아 사용하는 방향으로 정하는건 어떨까 제안합니다.

**Comment by adap8709** [comment]
저도 그렇게 생각합니다.
문제되었던 데이터 라벨링 문제도 해결할 수 있고, 정확성 측면에서도 긍정적입니다.
문장에서 욕설 부분을 찾기 위해 추후에 워드 임베딩에 대해 조사하고 의논해보아야 할 것 같습니다.
