### ISSUE TITLE
Word Embedding 사용 관련

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#25]
멘토님께서는 워드 임베딩이 필요하다고 말씀하셨습니다.
조사한 결과 Word Embedding 모델로 비슷한 단어, 즉 변형된 비속어를 찾아낼 수 있을 것으로 보입니다.
또한 좌우 문맥을 고려하는 기능을 구현할 수 있을 것으로 보입니다.

워드 임베딩의 사용은 필수적으로 보입니다만, 아직 어떤 라이브러리를 어떻게 사용해야 할지 감이 잡히지 않습니다.
이에 대해 팀원들과 논의하고 싶습니다. 아는 정보가 있다면 알려주시기 바랍니다.

**Comment by wan500kim** [comment]
저번에 제가 언급한 fasttext도 임베딩이 가능한 패키지라고 합니다. 아직 사용해보지 않아 아는 내용은 하나 없지만 찾아놓은 김에 fasttext를 사용하는 것은 어떨까요?

**Comment by adap8709** [comment]
조사한 결과 각 단어는 n-gram으로 벡터화하여
모르는 단어(OOV)에 대한 대응이 좋다고 하네요! 좋은 답변이 되었습니다.
FastText 방식으로 결정하겠습니다.
