### ISSUE TITLE
워드 임베딩 적용법

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#26]
공식 사이트에서 이미 학습된 한국어 버전의 fasttext를 다운받고 사용법을 찾아보았으나 제 이해력이 낮은 것인지 아직도 어디에 어떻게 적용시켜야 되는지 모르겠습니다. 멘토께서 말씀하신대로면 전처리 과정에 포함되는 부분이지만 임베딩에 관해서 도움을 요쳥합니다

**Comment by adap8709** [comment]
한국어에서의 FastText는 음절 단위와 자모 단위로 가능하다고 합니다.
자모 단위의 경우 음절 단위보다 오타나 노이즈 측면에서 더 좋은 성능을 기대볼 수 있다고 합니다.

**Comment by wan500kim** [comment]
네 성능은 좋다고는 하는데, 제 질문은 모델을 어떻게 적용시켜야하는지, 적용하면 어떤 역할을 하는지를 모르겠습니다

**Comment by adap8709** [comment]
현재 댓글을 형태소 단위로 분리 -> 자모 단위로 나누어 적용한다면
FastText로 사용할 수 있을 것 같습니다.
저도 해보지 않아서 잘 모르지만 가능할 것으로 예상합니다.

**Comment by wan500kim** [comment]
조금 더 찾아보니 cnn 모델링에 임베딩 과정을 넣어 전처리과정을 최소화하는 것이 효율적인 것 같네요. 모델링에 임베딩도 넣어서 같이 해주실수 있나요?

**Comment by adap8709** [comment]
알겠습니다. 말씀하신 대로 적용하면 될 듯 합니다.

**Comment by wan500kim** [comment]
감사합니다.
