### ISSUE TITLE
프로젝트 언어  선정

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#3]
역할 배분에 앞서 본인이 자신있는 언어, 개발 분야에 대해 적어주세요!

**Comment by adap8709** [comment]
언어: C, C++, python
개발 분야: backend

**Comment by wan500kim** [comment]
언어: C, C++, python
개발분야: 상관 없음

**Comment by adap8709** [comment]
인공지능 분야이므로 개발언어는 python이 좋을 것 같은데 어떤가요?

**Comment by wan500kim** [comment]
네 그렇게 합시다
