### ISSUE TITLE
순화 알고리즘 수정

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#32]
순화 알고리즘의 계획안에서는 욕설을 '글자 수가 맞는 무작위 단어로 치환'이라고 계획하였습니다.
구현 중에 생각해보니 단순 치환이 아닌 '순화'가 목적이기 때문에
글자 수별로 순화된 단어라고 할 수 있을만한 단어 리스트에서 랜덤으로 선택하는 것이 적절하다고 판단했습니다.
현재 순화 단어 리스트는 다음과 같습니다.

- 1글자: ['꽃', '꿀', '굿']
- 2글자: ['아잉', '어머', '좋아', '멋져']
- 3글자: ['사랑해', '나이스', '멋쟁이']
- 4글자 이상: ['아잉', '어머', '좋아', '굿','사랑해', '나이스']

4글자 이상의 경우 욕설의 수가 적기 때문에 위의 1~3글자 리스트에서 적절한 것을 추려 넣은 상태입니다.
적절한 단어가 있다면 댓글로 남겨주시면 추가하겠습니다.

**Comment by wan500kim** [comment]
단어는 비속어나 기분이 나쁜 단어만 아니면 상관 없다고 생각합니다.
만약 비속어 사이에 특수문자를 매우 많이 넣어, 예를 들면 시@@@@@@@@@@@@@@@@@@발이라 사용했을 경우, 4글자 이상으로 취급되나요? 아니면 비속어 자체가 2글자이니 2글자로 취급되나요?

**Comment by adap8709** [comment]
전처리에서 특수문자를 제거하도록 전처리하였기 때문에, input에서도 특수문자를 제거해야 할 듯 합니다.

**Comment by adap8709** [comment]
위의 질문에 답변하자면 2글자로 취급됩니다.

**Comment by wan500kim** [comment]
그렇군요. 그렇다면 앞서 말씀하신대로 4글자가 넘어가는 비속어는 흔치 않으니 위처럼 1글자, 2글자, 3글자, 4글자 이상으로 나누는 것이 좋을듯 합니다.
