### ISSUE TITLE
프로젝트 역할 분담

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#4]
먼저 데이터를 모으기 위한 크롤러
모델을 만들 프로그래머
모델을 적용시킬 프로그래머가 필요합니다

**Comment by wan500kim** [comment]
저는 무엇을 하던 상관 없습니다

**Comment by adap8709** [comment]
크롤링을 제가 해도 될까요?
데이터마이닝 강의를 듣고 있어서 원활하게 개발할 수 있을 것 같습니다.

**Comment by wan500kim** [comment]
그럼 하고난 다음 모델 설계는 같이 하도록 할까요?
동시에 할 수 있는 작업이 없으니 하나의 작업도 같이 하는 것이 좋을 것 같아요

**Comment by adap8709** [comment]
그 전에 전처리기를 만들어주시면 어떨까요?
모델부터는 과정이 순차적으로 이루어져야하니까 같이 만들거나 다시 한번 토론하는게 좋을 것 같습니다.

**Comment by wan500kim** [comment]
알겠습니다 그럼 전처리기를 만들고 대기하도록 하겠습니다
