### ISSUE TITLE
개발 현황 파악(2차)

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#48]
기말 발표 ppt 제작과 프로젝트 마무리를 위해 현재까지의 개발 현황을 적어주세요

**Comment by adap8709** [comment]
약간의 오류가 발생하긴 하나 계획안의 내용을 전부 완성했습니다.
(fasttext model, cnn model, 전처리 및 vectorize, 순화 알고리즘)
오류를 수정하고 실행가능한 하나의 .py 파일로 만들어 업로드하겠습니다.

**Comment by wan500kim** [comment]
flask는 틀은 다 잡아 놓았으니 수정본을 받으면 이에 맞게 버그 픽스만 하면 되는 상황입니다
