### ISSUE TITLE
peer-review, reviewer 입장

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#49]
reviewer입장에서 the creation조의 결과 보고서 초안을 보고 지적할만한 점 등을 적어주세요

**Comment by wan500kim** [comment]
1. 국내 차량 기준 EDR(사고기록 장치)이 부착되어 있으며 따라서 이미 더 효율적인 해결법이 실행된 상태이므로 문제가 해결되었다고 생각된다.
2. 만약 운전자이자 어플 사용자가 급발진 의심 사고로 인해 사망했을 경우 관련 데이터에 어떻게 접근 승인을 할 것인지 대책이 필요하다.
3. 블랙박스에 비해 싸지만 센서의 고장으로 빈번한 교체를 해야 한다면 경제적이지 못할 수도 있다.

**Comment by adap8709** [comment]
1. Problem 관련 comment
• Input 값에는 현재속도, 엑셀상태, 브레이크 상태가 있고, Output에 ‘운전자의 발 동작값’과 ‘운전자가 페달을 밟았는지 밟지 않았는지 판별값’이 있다. 여기서 ‘운전자의 발 동작값’이라는 단어가 모호하다. 엑셀을 얼마나 밟았는지를 의미하는 단어라면 앞의 ‘판별값’과 의미가 비슷하고, 엑셀을 밟는 발의 자세를 의미하는 단어라면 input 값에 발의 자세를 촬영하거나 인식할 수 있는 센서가 명시되어 있어야 한다.
• 급발진을 증명하려면 정확한 시간과 함께 페달 상황이 기록된 데이터를 저장 및 출력해야 한다고 하였다. 이를 Output에 명시해야 한다.

2. Solution 관련 comment
• 각 센서가 모바일 앱 상으로 정보를 전송하는 방법을 명시해야 한다.
• 각 센서들을 차량의 어느 부분에 설치할 것인지, 각 센서를 어떻게 연결할 지 명시해야 한다.
• 충격감지 센서는 사고 발생 시 파손될 가능성이 있다. 또한 자동 신고 기능에 관여하기 때문에 자칫하면 오인 신고의 가능성도 있다. 따라서 부품의 종류, 위치, 작동 방식, 신고 기준치 선정 등이 아주 정교해야 하는데, 이를 명시해야 한다.
• 센서로부터 기록된 데이터를 어디에 저장할 것인지, 얼마 동안 보관할 것인지 명시해야 한다.

3. 차별성 관련 comment
• 사고 상황은 자주 발생하는 상황이 아니며, 예측이 불가능하기에 항상 정교한 측정이 가능한 블랙박스를 사용한다. 이 어플리케이션의 급발진 판별 기능이 블랙박스와 비슷한 수준이 아니라면, 가격경쟁력 면에서 차별성이 있다고 보기 어렵다.

4. Evaluation 관련 comment
• 성능 검증을 위해 사용자의 실제 사고 데이터를 수집하는 것은 시간적으로 비현실적이다. 정확한 성능 평가를 위해서는 급발진 사고 재현이 필요할 것인데, 비용적인 문제가 있다. 성능 평가를 위해 어떤 방법을 사용할지 고려해야 한다.

5. 이하 관련 comment
• 기대효과 중 사고 위험 지역을 구체화한다는 내용이 있다. 이는 차량 내부가 아닌 다른 도로의 상황을 파악하는 기능이 필요한데, 구현이 까다로우며 네비게이션 등의 적합한 장치보다 나은 성능을 기대하기는 어렵다. 따라서 데이터를 이용한 다른 부가 서비스를 고안하는 것이 좋을 것 같다.
