### ISSUE TITLE
화면 모니터링 구현 가능성

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#5]
현재 주제는 화면에 보이는 모든 글자를 캡쳐해야만 합니다.
또한 해당 글자를 모자이크 하는 등의 기능도 추가해야 합니다.
이 경우 구현하기가 난해할 뿐더러 오히려 사용자에게 불편을 초래할 가능성도 있어 보입니다.

따라서 주제를 변경하는 것이 어떨 지 의견이 궁금합니다.

**Comment by wan500kim** [comment]
찾아본 결과 실시간 감시는 가능하지만 모니터 내의 단어들을 제시각각 판단하는 것은 무리라고 생각합니다

**Comment by adap8709** [comment]
차라리 함수처럼 문자열을 받아서 필터링 하도록 하는 것이 더 구현하기 쉬울 것 같습니다.

**Comment by wan500kim** [comment]
이미 크롤링을 했다면 아쉬우니 필터링 시스템이란 방향은 유지하도록 하죠

**Comment by adap8709** [comment]
크롤링 데이터는 모델에 활용할 수 있습니다.
다른 의견이 없으면 주제를 변경하려고 하는데 동의하시나요?

**Comment by wan500kim** [comment]
채팅 비속어 필터링을 말씀하시는거죠? 네 저는 괜찮습니다
