### ISSUE TITLE
Peer-review 받은 코멘트 & 답변

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#50]
### peer-review로 받은 comment들 입니다. 답변에 대해 논의하고자 합니다.

- (Solution) 특정 집단에서 사용하는 비속어의 의미를 담은 은어의 경우 평상시에 일반적으로 사용하는 단어도 비속어로 분류되곤 한다. 그 경우에는 일반적인 단어와 비속어로서의 단어의 형태가 같은데 이부분에 대해서는 어떻게 생각하는지 궁금하다. 

- (기대효과 및 발전방향) 커뮤니티, 게임, SNS등의 인터넷 환경에 실제로 적용되어 사용할 수 있다고 하였다. 특히 게임의 경우 기존에 모아둔 비속어데이터 뿐만 아니라 각 게임마다 존재하는 커뮤니티의 성격이 다르기 때문에 게임 커뮤니티에서 게임유저들이 주로 사용하는 비속어데이터를 다시 크롤링하여 추가한다면 더욱 정확도가 높아질 거라고 생각한다.

- (개발목표결과물) 결과보고서에 나와있는 개발목표결과물에서는 비속어를 순화하여 다른 단어로 나타낸다는 솔루션과 달리 비속어 필터링이 *로 되어있다. 솔루션에서 말한 것과 같이 비속어를 감지하고 그 비속어의 자리에 순화시킨 단어로 대체한 결과를 보여주는 것이 좋을 것 같다.

- (차별성) 크롤링을 통해 새로 생긴 욕설도 검열한다고 하였는데 온라인 커뮤니티의 경우 유행이 빠르고 비속어가 생성되는 경우가 많다. 그러니 주기적으로 크롤링을 통해 데이터를 모으고 데이터를 갱신하여 모델학습을 시키는 것이 좋을 것 같다.

- (Solution) 비속어를 한 문장에 사용하는 경우가 아니라 한 단어를 여러 문장으로 끊어서 하는 경우는 해당 방법으로 필터링이 어려울 것 같은데 해결 방안이 있는지

- (차별성) 이미 채팅에서 욕설을 멋쟁이, 사랑해 등과 같은 말로 변경해서 보여주는 게임들이 있는 걸로 안다. 중간에 숫자/특수문자를 섞어도 필터링이 되는데 이 서비스와 다른 점이 무엇이 있는지

- (Evaluation) 크롤링을 통해 데이터를 얻어오더라도 결국 새로 생긴 비속어는 직접 읽어보고 금칙어로 지정해줘야 할 것 같은데 이는 기존 필터링 서비스와의 차별점이 없어 보인다

- (차별성) 검열된 단어가 단순 검열하는 것이 아닌 순화한 단어로 치환하는 것이 차별성인데  순화한 단어를 문장의 의미에 맞는 단어가 아니면 상대방이 나에게 욕설을 했음을 단번에 알 수 있을것 같다. 이에 대한 해결방안은 있는지

- (Solution) 예를들어 띄어쓰기 문제로 아무 문제 없는 말이 욕이 되는 경우도 있습니다. 이러한 경우 해결방안이 있는지

- (Problem) 필터링을 쉽게 우회하는 것을 막더라도 사람들이 욕설을 하는 것을 막을 수 있을 지 궁급하다.

**Comment by wan500kim** [comment]
1번 그러한 경우 일부 수작업을 통해 유사 문자들을 정리해놓는 것이 최선일 것 같네요
2, 3, 4번 이미 결과보고서의 미래 전망에 포함된 내용이구요
5번 이러한 경우는 수작업이 필요하겠네요. 몇개의 댓글을 스택에 보관하며 여러 문구를 붙여 검사하는 등의 방법이 있겠지만 그 사이에 여러 의미 없는 문구가 들어간다면 이 또한 의미 없으니까요
6, 8번 앞으로 문맥에 맞는 단어로 치환하도록 개발할 예정입니다
7번 금칙어를 통하여 변형 비속어들까지 잡아낼 수 있는 것이 차이점으로 변형 문구들 하나하나 금칙어로 지정하는 것에 비해 매우 적은 인력이 소모됩니다
9번 그런 경우를 판단하기 위해 필요한 것이 임베딩이고, 그 과정을 통해 정확도가 높지는 않지만 어느정도 잡아낼 수는 있습니다
10번 사람들의 욕설 사용이 아닌 욕설 사용에 노출되는 빈도를 줄이는 것이 목표이므로 줄어들 것이라 기대하지 않습니다

**Comment by adap8709** [comment]
의견을 참고하여 답변을 작성해 보았습니다.
발표용 ppt를 첨부하니 검토해주시면 되겠습니다.

[peer-review_[바나나킥] 박영찬, 김완수.pptx](https://github.com/wan500kim/kickWorks/files/10200009/peer-review_.pptx)

**Comment by wan500kim** [comment]
검토 완료했습니다. 이슈를 닫겠습니다
