### ISSUE TITLE
최종 web에서 구동되는 코드에 대해

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#51]
Web에 대한 지식이 없어 담당자와 논의하고자 합니다.
구현한 코드는 bananaKick 함수에 string 인자를 주어 작동하도록 되어있습니다.
웹에서 이를 출력하려면 반환값만 주어도 되는지, print문으로 출력하는 것이 좋은지 궁금합니다

1. 최종 결과물이 함수 return 값 (문자열)
2. Print 문으로 결과물을 표시하기까지 코드에 포함

또한 함수를 1번 실행하고 코드를 종료할지, input()을 통해 종료할 때까지 입력을 계속 받도록 할지 결정해주시기 바랍니다.

**Comment by wan500kim** [comment]
print문으로 출력시 터미널에만 결과가 나오고 웹에는 표시되지 않습니다. 따라서 1번과 같이 return값으로 반환하여 화면에 표시되도록 해야 합니다

**Comment by wan500kim** [comment]
이는 flask 코드에 포함되는 내용이므로 조장님이 주신 파일은 수정할 것이 없습니다
따라서 이슈도 닫도록 하겠습니다
