### ISSUE TITLE
flask와 mode함수

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#52]
받은 파일에 필터링 결과를 분석해 보여줄지를 결정하는 mode함수를 제거할 것을 요청합니다.
mode==1일 경우 return값이 3개가 되고 이를 flask에서 구현하는데에 어려움이 있습니다

**Comment by adap8709** [comment]
해당 mode 기능은 개발 중 코드가 올바르게 작동되었는지 판단하고,
어느 부분을 욕설로 판단했는지, 그 확률은 무엇인지, 그로 인해 생성된 리스트는 무엇인지 등을 알 수 있어
전체 코드에서 제외해서는 안되는 중요한 요소입니다. (발표에서 사용 예정)

하지만 코드를 웹에서 구현하려면 return 값이 하나여야 한다고 하셨으므로
웹에 올릴 코드를 직접 수정하기를 권장드립니다.

**Comment by wan500kim** [comment]
그럼 flask에는 mode==0만 출력되도록 만들겠습니다
