### ISSUE TITLE
머신러닝 모델 선정

### ISSUE THREAD

**Issue by wan500kim** [wan500kim/kickWorks#6]
문장을 학습시키는 모델은 찾아본 결과 rnn과 bert가 가장 효율 좋다고 합니다
어떤 모델을 사용할까요?

**Comment by adap8709** [comment]
현재 논문 등의 자료를 추합해 보았을 때 CNN도 자연어 처리에 적합하다고 합니다.
기본적인 SVM로 인한 방식도 고려해 볼만 합니다.

**Comment by wan500kim** [comment]
cnn은 이미지 학습 모델이라 나오는데 문단 학습도 가능한가요?

**Comment by adap8709** [comment]
BERT의 경우 좋은 성능을 기대할 수 있을 것으로 보이나 알려진 정보가 적고 사용법이 어렵습니다.
CNN의 경우 논문 등의 정보도 많아 개발이 조금 더 수월하지 않을지 생각합니다.
다른 후보 모델이 있을까요?

**Comment by wan500kim** [comment]
rnn과 cnn은 친척뻘인것 같으니 cnn 사용도 무리는 없어 보입니다.
그럼 이참에 새로운 것 배운다 생각하고 cnn을 사용하여 만들도록 합시다

**Comment by adap8709** [comment]
네 일단은 CNN으로 선정하는 것이 좋아 보입니다.

**Comment by wan500kim** [comment]
그럼 cnn으로 결정하겠습니다
