### ISSUE TITLE
서비스 방법 및 예상 결과물

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#7]
3주차 ppt에 예상 결과물 항목이 있습니다.
저희 프로그램을 코드 상으로만 남겨놓지 말고 서비스 하는 방법을 생각해야 할 것 같습니다.
저는 웹 기반 동작을 생각하고 있는데 의견이 궁금합니다.

**Comment by wan500kim** [comment]
찾아보니 파이썬 패키지로도 서버를 구동시킬 수 있다고 합니다
아마 처음 정했던 주제를 구현하는 것보다는 쉽지 않을까 생각이 듭니다
만약 하게 된다면 제가 할테니 대신 모델 설계를 맡아주시겠어요?

**Comment by adap8709** [comment]
네 현재까지는 웹 기반 구동이 제일 유력해 보입니다.
크롤링 이후에 모델 설계까지 진행하는 것이 개발 상 매끄럽기 때문에
웹 서비스를 구현을 맡아주시면 제가 모델 설계까지 진행하겠습니다.

**Comment by wan500kim** [comment]
그럼 제가 서버 구현을 하는 것으로 하겠습니다
