### ISSUE TITLE
크롤링 범위 설정

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#8]
각종 커뮤니티에서 댓글을 크롤링 하려고 합니다.
학습 데이터는 욕설을 포함한 댓글과 포함되지 않은 댓글이 골고루 분포되어야 합니다.
어느 커뮤니티를 크롤링 하는 것이 좋을까요?
2곳 이상의 커뮤니티를 크롤링 하는 것이 나을까요?

**Comment by wan500kim** [comment]
비속어가 가장 없는 곳은 유튜브가 아닐까 생각이 듭니다
반대로 많은 곳은 디시나 루리웹 등이 유명한가봐요

**Comment by adap8709** [comment]
욕설이 없는 댓글을 주로 수집하기 위해 '유튜브'를,
욕설이 있는 댓글을 주로 수집하기 위해 최대 악질 커뮤니티로 유명한 '일간베스트'를 선정한다면
그 비율이 1:1 정도로 맞지 않을까 생각하는데 어떤가요?

**Comment by wan500kim** [comment]
제가 잘 몰라서 그러는데 크롤링 코드만 있다면 여러 사이트에서 조금씩 가져와도 되는 것 아닌가요?

**Comment by adap8709** [comment]
사이트 별로 html 구조가 달라서 호환되지 않는 경우가 대부분입니다.

**Comment by wan500kim** [comment]
그렇군요 그럼 처음 제안대로 대표 커뮤니티 하나씩 뽑아서 하는 것이 좋겠네요
그럼 동일하게 뽑힌 유튜브는 유지하고 비속어 사이트는 조금 더 평이 안좋은 일베가 좋긴 하겠네요

**Comment by adap8709** [comment]
그러면 유튜브오 일간베스트로 설정하겠습니다.
나중에 데이터가 모자라면 추가하는 식으로 진행하겠습니다.
