### ISSUE TITLE
데이터 라벨링 문제

### ISSUE THREAD

**Issue by adap8709** [wan500kim/kickWorks#9]
크롤링한 댓글 데이터는 몇십만개 단위로 예상됩니다.
지도 학습을 위해서는 각 댓글마다 욕설 여부를 라벨링 해주어야 합니다.
다만 저희는 2인 팀이므로 수작업으로 진행하기에는 무리가 있습니다.
해결 방법이 있을까요?

**Comment by wan500kim** [comment]
일단 시간이 있으니 남는 시간마다 친구들에게 부탁하여 최대한 해보죠
완전 무리라고 생각이 든다면 이미 태깅된 데이터를 구하는 것도 방법이긴 하지만 직접 구한 데이터를 쓰는 것이 더 의미있긴 해요

**Comment by adap8709** [comment]
현재 방안은 이렇습니다

- 지인들에게 수작업 라벨링 의뢰하기
- 높은 정확도가 검증된 욕설 여부 확인 알고리즘에 데이터 통과시키기
- 라벨링된 한국어 댓글 데이터 구하기

**Comment by wan500kim** [comment]
이미 친구들한테 밥사준다며 꼬셨는데도 안한다내요
이미 완성된 모델을 사용하는 것보다는 라벨링된 데이터를 사용하는게 그래도 조금 더 저희의 결과물이란 느낌이 나니까 저는 3번 방안이 좋을 것 같습니다

**Comment by adap8709** [comment]
그럼 당분간 라벨링된 데이터를 찾아보는 것으로 하죠!

**Comment by wan500kim** [comment]
크롤링 데이터가 언급된 김에 한가지 죄송스러운 소식을 전하겠습니다.
태깅을 하는데에 있어 너무 많은 시간이 소요되고 있으며 개발이 지연 되고 있습니다. 다른 태깅된 데이터를 찾아 쓰는 것이 이제는 불가피해 보입니다.

**Comment by adap8709** [comment]
라벨링된 데이터셋을 찾았습니다!
학습은 이를 사용하는 것으로 하고, 기존의 크롤링 내용은 워드 임베딩 모델에 사용하면 될 것 같습니다.
문제가 해결되어 다행입니다.
